alias 'tf=\'terraform\''
alias 'tfa=\'terraform destroy -force \''
alias 'tf=\'terraform\''
alias 'tfa=\'terraform destroy -force \''
alias 'tf=\'terraform\''
alias 'tfa=\'terraform destroy -force \''
alias 'tf=\'terraform\''
